name: So Long, My Past
description: 凡是过往，皆为序章
meta_description: 

aboutPage: true
encoding: utf-8
timezone: Asia/Shanghai

highlighter: rouge

paginate: 5
baseurl: 'https://alviezhang.github.io/so-long-my-past'
domain_name: 'https://alviezhang.github.io/so-long-my-past/'
google_analytics: 'UA-59721977-2'
disqus_shortname: 

# Details for the RSS feed generator
url:            'https://alviezhang.github.io/so-long-my-past/'
author:         '张三疯'

permalink:       /:year/:title/

exclude:
    - Makefile

gems: [jekyll-paginate]

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

